### ISSUE TITLE
Not working properly when noScript is false and removeReactHelmetAttrs is true

### ISSUE THREAD

**Issue by I-did-this** [shoonia/gatsby-plugin-no-javascript-utils#6]
{
      resolve: 'gatsby-plugin-no-javascript-utils',
       options: {
        **noScript: false,**
        noSourcemaps: false,
        removeGeneratorTag: false,
        **removeReactHelmetAttrs: true,**
        noInlineStyles: false,
        removeGatsbyAnnouncer: false,
      },
    }
    When **noScript is false** and **removeReactHelmetAttrs is true** in option, 
    its is only remove **data-react-helmet="true"** from **view source** of page,
    but not remove from **inspect element** view (F12)
    
    
![image](https://user-images.githubusercontent.com/64223403/131105431-613ec361-58ff-4d7e-be32-d29b4ac87b56.png)
![image](https://user-images.githubusercontent.com/64223403/131105504-4a5d908c-a1ef-4cdd-bead-36df3ef40c0c.png)

Its happens because react-helmet javascript attaching data-react-helmet="true" to mapped html tags.
As per SEO community **data-react-helmet="true"** attribute is not reliable for search engine crawlers.

**Comment by shoonia** [comment]
Hey, @yES-iAM !

The attributes `data-react-helmet` it's a part of library [react-helmet](https://github.com/nfl/react-helmet). Gatsby use this library for dynamically updating of tags in `<head>` section.

If you don't remove scripts in your site, then loaded scripts include a `react-hamlet` library that dynamically after loaded to changes your HTML.

You can check it: 

- Open Chrome DevTools.
- Navigate to the Network Tab and open the Throttling dropdown which is set to "No throttling" by default.
- Select Slow 3G
- Navigate to the Elements Tab
- Reload the Page

You can see that your page does not contain any data attributes. After loading a script, it changes a page.

**Comment by I-did-this** [comment]
Yes Shoonia, because of Gatsby use this library for dynamically updating of tags in <head> section, tags are being duplicate, and gives schema error in [google rich schema testing tool](https://search.google.com/test/rich-results).

ex.
```
<title>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</title>
<title data-react-helmet="true">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</title>

<script type="application/ld+json">Some schema code</script>
<script data-react-helmet="true" type="application/ld+json">Some schema code</script>
```

So in this case we must enable remove javascript from page like `noScript: true`

**Comment by shoonia** [comment]
The `data-react-helmet` attributes need for [react-helmet](https://github.com/nfl/react-helmet) library. If you don't use JavaScript then you don't need these attributes. But if you use JavaScript then you should not remove these attributes.

This current plugin exists for converting a Gatsby site to a static site without JavaScript. If you don't want to remove JavaScript from your site maybe you don't need this plugin.
